### PR TITLE
Fix translation of expires_in to Unix timestamp

### LINKED ISSUE #319: Expiration of access token processed incorrectly
From: https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/Connection.php#L467
```php
    private function getDateTimeFromExpires($expires)
    {
        if (!is_numeric($expires)) {
            throw new \InvalidArgumentException('Function requires a numeric expires value');
        }
        return time() + 600;
    }
```
The expires_in value is not used at all. The function basically says that the token will *always* expire in 10 minutes from *now*. Also, the naming of the function is wrong because it doesn't return a DateTime, and I've noticed a lot of `@var mixed` and `@param mixed`.

### PR DESCRIPTION
**Pull request by ameenross**
Also some clarification in docblocks, clearer function name

Fixes #319

### CODE REVIEW

File: src/Picqer/Financials/Exact/Connection.php [hunk 1]
```diff
@@ -464,25 +464,25 @@ private function acquireAccessToken()
         }
     }
 
-    private function getDateTimeFromExpires($expires)
+    private function getTimestampFromExpiresIn($expiresIn)
     {
-        if (!is_numeric($expires)) {
+        if (!is_numeric($expiresIn)) {
```
Comment (bixelsnl) [inline src/Picqer/Financials/Exact/Connection.php]: Unrelated to your PR, but it may be feasible to use `ctype_digit()` here rather than `is_numeric()`. According to https://tools.ietf.org/html/rfc6749#section-5.1 , this field contains the number of seconds so `is_numeric()` may allow a bit more than we would want.

File: src/Picqer/Financials/Exact/Connection.php [hunk 2]
```diff
@@ -464,25 +464,25 @@ private function acquireAccessToken()
         }
     }
 
-    private function getDateTimeFromExpires($expires)
+    private function getTimestampFromExpiresIn($expiresIn)
```
Comment (bixelsnl) [inline src/Picqer/Financials/Exact/Connection.php]: Might want to add a docheader, since you are here :)

Comment (ameenross) [reply src/Picqer/Financials/Exact/Connection.php]: Well, I almost wanted to remove it completely because it's such a simple expression that might as well be inlined. It's used only once as well...

File: src/Picqer/Financials/Exact/Connection.php (hunk 1 above)
Comment (ameenross) [reply src/Picqer/Financials/Exact/Connection.php]: Again, I actually just wanted to remove this function.

I don't think Exact would ever return anything other than an int. And if they do, it's a horrible bug on their side which you shouldn't attempt to handle IMO.

Comment (stephangroen) [reply src/Picqer/Financials/Exact/Connection.php]: Although on a lot of other places we do rely on what Exact returns as documented, I think in this case `ctype_digit` is a better check. Could you please change the check? I'd love to have that improvement within this PR.

**Comment by stephangroen** [comment]
Very good catch, thank you!

File: src/Picqer/Financials/Exact/Connection.php (hunk 2 above)
Comment (stephangroen) [reply src/Picqer/Financials/Exact/Connection.php]: For the sake of having everything documented, could you please add them?

It's only used once, but inline it wouldn't incorporate the checks that are done now.

File: src/Picqer/Financials/Exact/Connection.php (hunk 1 above)
Comment (ameenross) [reply src/Picqer/Financials/Exact/Connection.php]: Well, since the `+` operator is used on it, anything invalid and potentially dangerous would still just yield an int or a float and therefore be pretty much harmless, but I digress.

File: src/Picqer/Financials/Exact/Connection.php [hunk 3]
```diff
@@ -464,25 +464,30 @@ private function acquireAccessToken()
         }
     }
 
-    private function getDateTimeFromExpires($expires)
+    /**
+     * Translates expires_in to a Unix timestamp.
+     * @param int $expiresIn Number of seconds until the token expires.
```
Comment (bixelsnl) [inline src/Picqer/Financials/Exact/Connection.php]: Sorry, slight nuance - the value returned in the JSON is a `string` (which is also what `ctype_digit()` needs, as feeding it `int`s may yield unexpected results; see http://php.net/manual/en/function.ctype-digit.php#example-6311)
